{
    'name': 'Automotive & Spare Parts Management',
    'version': '19.0.1.1.0',
    'category': 'Services',
    'summary': 'Vehicle spare parts linked to products, warehouses, purchase and sales',
    'author': 'Osama Shoaib',
    'license': 'LGPL-3',
    'depends': ['fleet', 'mail', 'stock', 'purchase', 'sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'security/vehicle_record_rules.xml',
        'views/spare_part_views.xml',
        'views/fleet_vehicle_views.xml',
        'report/vehicle_spare_parts_report.xml',
        'report/adv_saleorder_report.xml',
        'wizard/sale_order_report_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
}
